---
# pre-commit install --allow-missing-config
# pre-commit autoupdate
# pre-commit run --all-files --color auto
exclude: |
  (?x)^(
    \.pre-commit-config\.yaml$
  )
fail_fast: true
default_stages:
  - pre-commit
default_install_hook_types:
  - pre-commit
repos:
  - repo: local
    hooks:
      - id: pytest
        name: "pytest | run unit tests"
        entry: pytest -vv --color=yes --tb=no
        language: system
        types:
          - python
        pass_filenames: false
        always_run: true
